# Generated by Django 5.2.1 on 2025-05-20 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="House",
            fields=[
                ("house_id", models.AutoField(primary_key=True, serialize=False)),
                ("house_num", models.BigIntegerField()),
                ("address", models.CharField(default="정보없음", max_length=255)),
                ("agent_comm", models.CharField(blank=True, max_length=255, null=True)),
                ("agent_info", models.CharField(default="정보없음", max_length=255)),
                ("area_size", models.CharField(default="정보없음", max_length=255)),
                ("availabe_from", models.CharField(default="정보없음", max_length=255)),
                ("building_type", models.CharField(default="정보없음", max_length=255)),
                ("built_date", models.CharField(blank=True, max_length=255, null=True)),
                ("deposit_type", models.CharField(default="정보없음", max_length=255)),
                ("direction", models.CharField(default="정보없음", max_length=255)),
                ("dong", models.CharField(default="정보없음", max_length=255)),
                ("floor", models.CharField(default="정보없음", max_length=255)),
                ("gu", models.CharField(default="정보없음", max_length=255)),
                ("house_explanations", models.TextField(blank=True, null=True)),
                ("house_feature", models.TextField(blank=True, null=True)),
                ("img_url", models.TextField(blank=True, null=True)),
                (
                    "management_fee",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("options", models.TextField(blank=True, null=True)),
                ("parking", models.CharField(default="정보없음", max_length=255)),
                ("posted_at", models.CharField(default="정보없음", max_length=255)),
                ("price", models.CharField(default="정보없음", max_length=255)),
                ("rooms_count", models.CharField(default="정보없음", max_length=255)),
                ("title", models.CharField(default="정보없음", max_length=255)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("apt_name", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
