pipeline {
    agent any

    environment {
        IMAGE_NAME = "koreatstm/malhaebang"
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/MalhaeBang/malhaebang-backend.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('MalhaeBangWebServer') {
                    script {
                        withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                            sh "docker login -u $DOCKER_USER -p $DOCKER_PASS"
                            sh "docker build -t ${IMAGE_NAME} ."
                        }
                    }
                }
            }
        }

        stage('Push to DockerHub') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                        sh "docker push ${IMAGE_NAME}"
                    }
                }
            }
        }
    }
}