apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "malhaebang.fullname" . }}-recommendsimilar-cache-pvc
  labels:
    {{- include "malhaebang.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # 캐시 파일은 작으므로 1GB면 충분
  storageClassName: gp2 