apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "malhaebang.fullname" . }}-nlp-data-pvc
  labels:
    {{- include "malhaebang.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2 