apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: malhaebang

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: ${ECR_REGISTRY}/malhaebang-web
    newTag: latest 