apiVersion: v1
kind: Secret
metadata:
  name: malhaebang-web-secret
  namespace: malhaebang
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD_BASE64}  # base64로 인코딩된 비밀번호
  JWT_SECRET: ${JWT_SECRET_BASE64}  # base64로 인코딩된 JWT 시크릿 